### ISSUE TITLE
Add functionality - MD5 Hash

### ISSUE THREAD

**Issue by killamjr** [EricZimmerman/RBCmd#1]
the recycle bin $I files also contain the MD5 hash of the deleted file, please add this functionality.

attached a screenshot of an example of the output from flashback data's "I File Parser Tool" compared to RBCmd
![xebar9pf](https://user-images.githubusercontent.com/946258/57577249-9519d700-7438-11e9-9a73-217249a71598.png)

**Comment by EricZimmerman** [comment]
as I mentioned on Twitter can you show me a screenshot of the hexadecimal contents of the dollar I file where you actually can see the MD5. because having it be in the artifact is different than a tool generating it. And if I had a hash it probably won't be md5

**Comment by killamjr** [comment]
yep confirmed i think you are correct, the MD5 that flashback data's tool is pulling back is just the hash of the i file itself and not the original file's hash. I'll just close this out
